### ISSUE TITLE
Tf recreate registry although nothing has changed

### ISSUE THREAD

**Issue by kaje783** [goharbor/terraform-provider-harbor#302]
**Describe the bug**
During a reapply terraform does not recognize that nothing has changed and deletes the registry and recreates it.

**To Reproduce**

1.  Install Harbor version 2.7.1
  - https://goharbor.io/docs/2.7.0/install-config/
  - harbor.yml config:
```
hostname: <harbor>

# http related config
http:
  port: 8080

harbor_admin_password: testpw

database:
  password: root123
  max_idle_conns: 100
  max_open_conns: 900

data_volume: /data

trivy:
  ignore_unfixed: false
  skip_update: false
  offline_scan: false
  security_check: vuln
  insecure: false

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 2.7.0

proxy:
  http_proxy: <proxy-addresse:proxy-port>
  https_proxy:  <proxy-addresse:proxy-port>
  no_proxy: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.1
  
  components:
    - core
    - jobservice
    - clair

upload_purging:
  enabled: true
  age: 168h
  interval: 24h
  dryrun: false

cache:
  enabled: false
  expire_hours: 24
```

2. Tf config
```
terraform {
  required_providers {
    harbor = {
      source = "goharbor/harbor"
      version = "3.8.3"
    }
  }
}

provider "harbor" {
    url      = <harbor_url>
    username = <harbor_username>
    password = <harbor_password>
}

resource "harbor_registry" "docker" {
  provider_name = "docker-hub"
  name          = "test"
  endpoint_url  = "https://hub.docker.com"
}
```
3. apply, reapply and reapply tf
```
#terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # harbor_registry.docker will be created
  + resource "harbor_registry" "docker" {
      + endpoint_url  = "https://hub.docker.com"
      + id            = (known after apply)
      + insecure      = false
      + name          = "test"
      + provider_name = "docker-hub"
      + registry_id   = (known after apply)
      + status        = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
harbor_registry.docker: Creating...
harbor_registry.docker: Creation complete after 2s [id=/registries/1]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
#terraform apply -auto-approve
harbor_registry.docker: Refreshing state... [id=/registries/1]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
#terraform apply -auto-approve
harbor_registry.docker: Refreshing state... [id=/registries/1]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # harbor_registry.docker must be replaced
-/+ resource "harbor_registry" "docker" {
      + endpoint_url  = "https://hub.docker.com"
      ~ id            = "/registries/1" -> (known after apply)
      + name          = "test"
      + provider_name = "docker-hub" # forces replacement
      ~ registry_id   = 0 -> (known after apply)
      + status        = (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
harbor_registry.docker: Destroying... [id=/registries/1]
harbor_registry.docker: Destruction complete after 0s
harbor_registry.docker: Creating...
harbor_registry.docker: Creation complete after 2s [id=/registries/2]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

**Expected behavior**
Terraform recognizes that no change happens

**Additional context**

- Provider Version [3.8.3]
- Terraform Version [1.3.9]
- Harbor Version [2.7.1]
